# 线性代数

## 张量的运算

In [3]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

In [4]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
x = x.reshape(2,2)

x

tensor([[0, 1],
        [2, 3]])

In [9]:
x.shape

torch.Size([2, 2])

## 矩阵的转置

In [10]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
A.T
# A矩阵的转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

### 对称矩阵 B等于其转置

In [12]:
B = torch.tensor([[1, 2 ,3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [13]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 矩阵的运算

### 一些常规的运算

In [14]:
C = torch.arange(24).reshape(2, 3, 4)
C

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
D = torch.arange(12).reshape(2, 6)
D

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [16]:
E = A.clone() 
# 为E分配了新的地址
A, A + E, id(A) == id(E)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]),
 False)

In [17]:
A * E 
# 哈达玛积

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [18]:
a = 2
a + A, (a * A).shape

(tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13],
         [14, 15, 16, 17],
         [18, 19, 20, 21]]),
 torch.Size([5, 4]))

### 求任意形状张量的元素和

In [19]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190))

#### 按照指定轴进行元素求和

In [20]:
F = torch.arange(40).reshape(2, 4, 5)
F.shape, F.sum()

(torch.Size([2, 4, 5]), tensor(780))

In [21]:
F

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]])

- 按照那个维度进行求和，就要消灭哪个维度，最终就没有这个维度啦

In [22]:
F_sum_axis0 = F.sum(axis = 0)
F_sum_axis0, F_sum_axis0.shape

(tensor([[20, 22, 24, 26, 28],
         [30, 32, 34, 36, 38],
         [40, 42, 44, 46, 48],
         [50, 52, 54, 56, 58]]),
 torch.Size([4, 5]))

In [23]:
F_sum_axis1 = F.sum(axis = 1)
F_sum_axis1, F_sum_axis1.shape

(tensor([[ 30,  34,  38,  42,  46],
         [110, 114, 118, 122, 126]]),
 torch.Size([2, 5]))

In [24]:
F_sum_axis2 = F.sum(axis = 2)
F_sum_axis2, F_sum_axis2.shape

(tensor([[ 10,  35,  60,  85],
         [110, 135, 160, 185]]),
 torch.Size([2, 4]))

In [25]:
F_sum_axis01 = F.sum(axis = [0, 1])
F_sum_axis01, F_sum_axis01.shape

(tensor([140, 148, 156, 164, 172]), torch.Size([5]))

In [26]:
F_sum_axis012 = F.sum(axis = [0, 1, 2])
F_sum_axis012, F_sum_axis012.shape

(tensor(780), torch.Size([]))

### 求矩阵的均值

In [27]:
G = torch.arange(12, dtype = torch.float32).reshape(3, 4)
G.mean(), G.sum() / G.numel()

(tensor(5.5000), tensor(5.5000))

In [28]:
G

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
G.mean(axis = 0)

tensor([4., 5., 6., 7.])

In [30]:
G.mean(axis = 1)

tensor([1.5000, 5.5000, 9.5000])

### 计算均值和求和保持轴数不变

In [31]:
# 通过keepdims = True可以保持被消除的那一维度，那一维度保留为1，直观感受为外面会套很多括号
sum_G = G.sum(axis = 1, keepdims = True)
sum_G

tensor([[ 6.],
        [22.],
        [38.]])

In [32]:
sum_F = F.sum(axis = 1, keepdims = True)
sum_F, sum_F.shape

(tensor([[[ 30,  34,  38,  42,  46]],
 
         [[110, 114, 118, 122, 126]]]),
 torch.Size([2, 1, 5]))

In [33]:
F_sum_axis1 = F.sum(axis = 1)
F_sum_axis1, F_sum_axis1.shape

(tensor([[ 30,  34,  38,  42,  46],
         [110, 114, 118, 122, 126]]),
 torch.Size([2, 5]))

### 这样就可以保证在利用广播机制时，两个参加运算的矩阵维度相同，可以进行运算

In [34]:
F / sum_F

tensor([[[0.0000, 0.0294, 0.0526, 0.0714, 0.0870],
         [0.1667, 0.1765, 0.1842, 0.1905, 0.1957],
         [0.3333, 0.3235, 0.3158, 0.3095, 0.3043],
         [0.5000, 0.4706, 0.4474, 0.4286, 0.4130]],

        [[0.1818, 0.1842, 0.1864, 0.1885, 0.1905],
         [0.2273, 0.2281, 0.2288, 0.2295, 0.2302],
         [0.2727, 0.2719, 0.2712, 0.2705, 0.2698],
         [0.3182, 0.3158, 0.3136, 0.3115, 0.3095]]])

In [35]:
F

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]])

### 矩阵的点积

In [36]:
G = torch.arange(4, dtype=torch.float32)
H = torch.ones(4, dtype=torch.float32)
G, H, torch.dot(G, H)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [37]:
torch.sum(G * H)

tensor(6.)

In [38]:
(G * H).sum()

tensor(6.)

In [39]:
G.shape

torch.Size([4])

### 矩阵和向量的乘法

In [40]:
H = torch.arange(20, dtype=torch.float32).reshape(5, 4)
I = torch.arange(4, dtype=torch.float32)

In [41]:
torch.mv(H, I)

tensor([ 14.,  38.,  62.,  86., 110.])

In [42]:
torch.mv(H, G)

tensor([ 14.,  38.,  62.,  86., 110.])

### 矩阵和矩阵的乘法

In [43]:
J = torch.arange(20, dtype=torch.float32).reshape(4, 5)
torch.mm(H, J)

tensor([[ 70.,  76.,  82.,  88.,  94.],
        [190., 212., 234., 256., 278.],
        [310., 348., 386., 424., 462.],
        [430., 484., 538., 592., 646.],
        [550., 620., 690., 760., 830.]])

### 向量和矩阵的范数
- norm操作求的是向量的L2范数，矩阵的F范数
$$
\|\mathbf{v}\|_2 = \sqrt{\sum_{i=1}^n v_i^2}
$$

$$
\|\mathbf{X}\|_F = \sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{ij}^2}
$$

In [44]:
HJnorm = torch.norm(torch.mm(H, J))
HJnorm

tensor(2231.1208)