In [18]:
import torch
import numpy as np

- 张量表示一个数值组成的数组，这个数组可能有多个维度

In [19]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

通过`shape`属性访问张量的形状
通过`numel()`访问张量中元素的总数

In [20]:
x.shape

torch.Size([12])

In [21]:
x.numel()

12

- 可以通过调用reshape函数来改变一个张量的形状，但是不改变这个张量的中元素的数量和元素值

In [22]:
new_x = x.reshape(3, 4)
new_x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [23]:
new_x_2 = x.reshape(6, 2)
new_x_2

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

In [24]:
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [25]:
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [26]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [27]:
x = torch.arange(12, dtype = torch.float32).reshape(3, 4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim = 0),torch.cat((x, y), dim = 1) 

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
x.sum() 

tensor(66.)

In [30]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

# 广播机制
- 先将两个张量扩展成有每一维度中最大值构成的张量
- 例如：下面一个$3*1$的张量和一个$1*2$的张量相加，最后的到的结果是一个$3*2$的张量

In [31]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [32]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

- 使用-1访问张量中的最后一个元素

In [33]:
a[-1]

tensor([2])

In [34]:
a[1:3]

tensor([[1],
        [2]])

In [35]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
x[1, 2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

- 为多个元素，通过查找区域为多个元素进行赋值

In [37]:
x[0:2, 0:2] = 12
x

tensor([[12., 12.,  2.,  3.],
        [12., 12.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

- 避免内存问题

In [38]:
before = id(y)
y = y + x
id(y) == before

False

- 执行原地操作，可以想下面这么整

In [39]:
z = torch.zeros_like(y)
# zero_like(y)表示z的形状和数据类型和y是一样的，但是所有元素的值都是0
print("id(z): ", id(z))
z[:] = x + y
print("id(z): ", id(z))

id(z):  5076162816
id(z):  5076162816


In [40]:
before = id(x)
x += y
before == id(x)

True

- Numpy 和 Torch之间的张量的转化

In [41]:
A = x.numpy()
A

array([[26., 25.,  8.,  9.],
       [25., 26., 21., 18.],
       [20., 21., 22., 23.]], dtype=float32)

In [42]:
B = torch.tensor(A)
B

tensor([[26., 25.,  8.,  9.],
        [25., 26., 21., 18.],
        [20., 21., 22., 23.]])

In [43]:
type(A), type(B)

(numpy.ndarray, torch.Tensor)

- 大小为1的张量可以转化为python的标量

In [44]:
a = torch.tensor([3.5])
a, int(a), float(a)

(tensor([3.5000]), 3, 3.5)

In [48]:
z = torch.arange(24).reshape(2,3,4)
z

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [49]:
a = z.numpy()
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
print(a.max(axis = 0))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [52]:
print(a.max(axis = (0, 1)))

[20 21 22 23]


In [53]:
k = torch.arange(12).reshape(3,4)
g = k.numpy()
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
print(g.max(axis = 0))

[ 8  9 10 11]
