## What is a Tensor?

### 创建一个tensor

- 常量和向量通常用小写字母来表示
- 矩阵和张量通常用大写字母来表示

In [54]:
import torch

In [55]:
print(torch.__version__)

2.4.1


In [56]:
# 创建一个常量，值为7，0维张量
scalar = torch.tensor(7)

In [57]:
scalar

tensor(7)

In [58]:
scalar.ndim

0

In [59]:
TENSOR = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]]])

In [60]:
TENSOR

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [61]:
TENSOR.ndim

4

In [62]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [63]:
TENSOR[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [64]:
TENSOR[0][0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [65]:
TENSOR[0][0][0]

tensor([1, 2, 3])

In [66]:
TENSOR[0][0][0][0]

tensor(1)

### 创建一个random tensor

- 为什么要使用random tensor呢？
- 因为许多神经网络的训练都是从random tensor开始的，随机的数能更好的表示数据

`start with random numbers -> look at data -> update random numebrs -> look at data -> update random numbers -> ...`

Torch.rand - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [67]:
# create a random tensor of size [3, 4]

random_tensor = torch.rand(3, 4)

In [68]:
random_tensor

tensor([[0.5273, 0.3559, 0.3121, 0.6394],
        [0.0758, 0.1926, 0.3885, 0.8590],
        [0.7229, 0.1401, 0.0044, 0.9996]])

In [69]:
random_tensor.ndim

2

In [70]:
random_tensor_2 = torch.rand(10, 10, 10)
random_tensor_2

tensor([[[6.4042e-01, 1.6824e-01, 4.4650e-01, 4.6604e-01, 2.1089e-02,
          3.6925e-01, 6.3193e-01, 7.7767e-01, 3.4610e-01, 6.8252e-01],
         [2.7281e-01, 4.4164e-02, 6.7652e-01, 7.6465e-01, 7.9856e-01,
          4.7576e-01, 2.7705e-01, 4.4536e-02, 4.5006e-01, 2.1996e-01],
         [2.4056e-01, 7.8353e-01, 8.7501e-01, 1.2139e-01, 6.3964e-01,
          4.2565e-01, 2.2357e-01, 7.4199e-01, 8.7797e-01, 1.1005e-01],
         [7.6061e-01, 4.5481e-01, 3.6235e-01, 4.6693e-02, 4.9445e-01,
          9.1158e-02, 6.4800e-01, 4.5538e-01, 2.7223e-01, 9.8484e-01],
         [1.5020e-01, 9.8159e-01, 7.0798e-01, 3.8011e-01, 1.3972e-01,
          9.8451e-01, 4.7582e-01, 4.3353e-01, 3.6383e-01, 8.3942e-01],
         [7.9280e-01, 9.2623e-01, 2.6389e-01, 6.7390e-01, 7.8750e-01,
          3.9002e-01, 7.2361e-02, 6.9357e-01, 4.3819e-01, 9.8108e-01],
         [8.2142e-01, 8.1958e-01, 5.1234e-01, 5.5544e-01, 9.0010e-01,
          6.5551e-01, 7.1931e-01, 7.7559e-01, 3.8341e-01, 5.8654e-01],
         [1.6

In [71]:
random_tensor_2.ndim

3

In [72]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
# height, width, color channels(rgb)
random_image_size_tensor.shape, random_image_size_tensor.size(), random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

### zeros and ones tensor


In [73]:
# creating a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [74]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [75]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [76]:
ones * random_tensor

tensor([[0.5273, 0.3559, 0.3121, 0.6394],
        [0.0758, 0.1926, 0.3885, 0.8590],
        [0.7229, 0.1401, 0.0044, 0.9996]])

In [77]:
random_tensor.sum(axis = 0)

tensor([1.3260, 0.6886, 0.7050, 2.4981])

In [78]:
ones.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [79]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
zero_to_thousand_step_77 = torch.arange(start=0,
                                        end =  1000,
                                        step= 77                      
                                        )
zero_to_thousand_step_77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [81]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

- **Note:** Tensor datatypes is one of the 3 big erros you'll run into PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device
   1. 如果两个TensorFlow不在一个设备上，一个在CPU上，一个在GPU上

### Getting information from tensors(tensor attributes)

1. to get datatype from a tensor —— use `tensor.dtype`
2. to get shape from a tensor —— use `tensor.shape`
3. to get device from a tensor —— use `tensor.device`

In [82]:
float_32_tensor = torch.tensor([1, 2, 3],
                               device="cuda", # What device is your tensor on
                               dtype=torch.float32, # What datatype is the tensor
                               requires_grad=True) # Whether or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float32

In [83]:
float_32_tensor.device

device(type='cuda', index=0)

In [84]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor.dtype

torch.float16

In [85]:
tensor_mul = float_16_tensor * float_32_tensor

In [86]:
tensor_mul.dtype

torch.float32

In [87]:
# Creating a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8973, 0.6691, 0.2112, 0.5859],
        [0.2440, 0.2204, 0.4296, 0.7690],
        [0.3252, 0.4518, 0.0121, 0.4199]])

In [88]:
# Find out details about some tensor

print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8973, 0.6691, 0.2112, 0.5859],
        [0.2440, 0.2204, 0.4296, 0.7690],
        [0.3252, 0.4518, 0.0121, 0.4199]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operation include:
- 加法
- 减法
- 乘法
- 除法
- 矩阵相乘 


In [89]:
# create a tensor

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [90]:
tensor - 100

tensor([-99, -98, -97])

In [91]:
tensor

tensor([1, 2, 3])

In [92]:
# multiplication

tensor * 10
tensor

tensor([1, 2, 3])

In [93]:
tensor - 10

tensor([-9, -8, -7])

In [94]:
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


#### Matrix multiplication

two main ways of performing multiplication:
1. element-wise multiplication
2. matrix multiplication

There are two main rules that preforming matrix multiplicatoin needs to satisfy:
1. The **inner dimensions** must match
   1. `(3, 2) @ (3, 2)`报错
   2. `(3, 2) @ (2, 3)` 和 `(2, 3) @ (3, 2)`都不会报错
2. The resulting matrix has the shape of the **outer dimensions**
   1. `(3, 2) @ (2, 3) -> (3, 3)`
   2. `(2, 3) @ (3, 2) -> (2, 2)`  

In [95]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equels: {(tensor * tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equels: tensor([1, 4, 9])


In [96]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [97]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [98]:
tensor_1 = torch.rand(3, 2)
tensor_2 = torch.rand(2, 3)

In [99]:
%%time
torch.matmul(tensor_1, tensor_2)

CPU times: total: 0 ns
Wall time: 1 ms


tensor([[0.6835, 0.4468, 0.4217],
        [0.7926, 0.5044, 0.5998],
        [0.4488, 0.3179, 0.0797]])

### One of the most common errors in dl: shape errors

In [100]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# torch.mm()
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [101]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### 使用transpose

- 转置

In [201]:
# .T表示transpose

tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [202]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [52]:
# 当B转置之后， 两个矩阵就可以实现矩阵乘法

print(f"tensor_A的形状是{tensor_A.shape}, tensor_B的形状是{tensor_B.shape}")
print(f"B矩阵转置之后，tensor_A的形状是{tensor_A.shape}， tensor_B的形状是{tensor_B.T.shape}")
print(f"Multiplying {tensor_A.shape} @ {tensor_B.T.shape}")
print(f"Output: {torch.mm(tensor_A, tensor_B.T)}")
print(f"Output's Shape: {torch.mm(tensor_A, tensor_B.T).shape}")

tensor_A的形状是torch.Size([3, 2]), tensor_B的形状是torch.Size([3, 2])
B矩阵转置之后，tensor_A的形状是torch.Size([3, 2])， tensor_B的形状是torch.Size([2, 3])
Multiplying torch.Size([3, 2]) @ torch.Size([2, 3])
Output: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output's Shape: torch.Size([3, 3])


### Finding the max, min, mean, sum, etc(tensor aggregation)

In [56]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [54]:
# Find the min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [55]:
# Find the max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [57]:
# Find the mean
# 输入的张量元素必须是float32

x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
x.type(torch.float32).mean()

tensor(45.)

In [59]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [60]:
!pip show torch

Name: torch
Version: 2.4.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: f:\.conda\d2l-zh\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision


In [61]:
!pip show d2l

Name: d2l
Version: 1.0.3
Summary: Dive into Deep Learning
Home-page: https://d2l.ai
Author: D2L Developers
Author-email: d2l.devs@gmail.com
License: MIT-0
Location: f:\.conda\d2l-zh\lib\site-packages
Requires: jupyter, matplotlib, matplotlib-inline, numpy, pandas, requests, scipy
Required-by: 


In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

发现了一个区别函数和属性的方法：
- 在提示中
- 属性前面是一个黑板擦
- 方法前面是一个立方体

In [63]:
x.argmin()

tensor(0)

In [65]:
tensor_X = torch.rand(size=(10,2))
tensor_X

tensor([[0.3234, 0.5551],
        [0.4348, 0.6957],
        [0.9572, 0.0127],
        [0.9403, 0.0761],
        [0.1717, 0.8251],
        [0.2687, 0.9575],
        [0.6368, 0.8102],
        [0.6707, 0.2779],
        [0.4250, 0.5594],
        [0.2983, 0.9217]])

In [69]:
# dim=0 表示沿着第0维（行）方向找最小值的索引
# 返回每列的最小值所在的行索引
# 结果是一个形状为[2]的张量，对应tensor_X的两列
tensor_X.argmin(dim=0)

tensor([4, 2])

### Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping: 将输入的tensor改变为指定的形状
- View: 功能与reshape类似，但是返回的是原张量的视图
- Stacking: 将多个张量沿着新的维度堆叠起来
- Squeeze: 移出所有大小为1的维度
- Unsqueeze: 在指定位置添加一个大小为1的维度
- Permute: 改变张量的维度顺序

In [70]:
x = torch.arange(1, 10, dtype=torch.float32)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
x.reshape(3, 3), x.size()

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([9]))

In [74]:
# Change the view
z = x.view(1, 9)
z, z.shape()

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
# changing z changes x (because a viwe of z shares the same memory as the original input)
z[0][0] = 5
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
x_stacked_1 = torch.stack([x, x, x, x], dim=1)
x_stacked_1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [82]:
x_reshaped = torch.arange(1., 10.)
x_reshaped, x_reshaped.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [85]:
x_reshaped = x_reshaped.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape
x_squeezed = x_reshaped.squeeze()

In [90]:
# torch.unsqueezed() -- adda a single dimension to a target tensor at a specific dim

print(f"Previous squeezed target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")


# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed_1}")
print(f"New shape: {x_unsqueezed_1.shape}")

Previous squeezed target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [108]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original =  torch.rand(size=(3, 4, 5))
x_original.shape

torch.Size([3, 4, 5])

In [94]:
# 使用permute操作
# 将原来第2维度的放在新的第0维度
# 原来第0维度放在新的第1维度
# 原来第1维度放在新的第2维度
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([5, 3, 4])

### Indexing(selecting data from tensors)


In [53]:
x = torch.arange(1, 10).reshape(shape=(1, 3, 3))
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [99]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [102]:
x[0][0][0]

tensor(1)

In [103]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [104]:
x[:, 1]

tensor([[4, 5, 6]])

In [105]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [106]:
x[:, 1, 1]

tensor([5])

In [102]:
x[0, 0, :]

tensor([1, 2, 3])

In [106]:
# index on x to return 9

x[0, 2, 2]

tensor(9)

In [107]:
# index on x to return 3 6 9
x[:, :, 2]

tensor([[3, 6, 9]])

### Interact with numpy
 

In [110]:
import numpy as np

array = np.arange(1., 10.)
array

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [111]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [112]:
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [113]:
array.dtype

dtype('float64')

In [114]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [115]:
# change the value of array, see what will do this to tensor
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [116]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [117]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility(trying to take random out of random)

In short how a neural network learns:

`start with random numebrs -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**