## What is a Tensor?

### 创建一个tensor

- 常量和向量通常用小写字母来表示
- 矩阵和张量通常用大写字母来表示

In [32]:
import torch

In [33]:
print(torch.__version__)

2.4.1


In [34]:
# 创建一个常量，值为7，0维张量
scalar = torch.tensor(7)

In [35]:
scalar

tensor(7)

In [36]:
scalar.ndim

0

In [37]:
TENSOR = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]]])

In [38]:
TENSOR

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [39]:
TENSOR.ndim

4

In [40]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [41]:
TENSOR[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [42]:
TENSOR[0][0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [43]:
TENSOR[0][0][0]

tensor([1, 2, 3])

In [44]:
TENSOR[0][0][0][0]

tensor(1)

### 创建一个random tensor

- 为什么要使用random tensor呢？
- 因为许多神经网络的训练都是从random tensor开始的，随机的数能更好的表示数据

`start with random numbers -> look at data -> update random numebrs -> look at data -> update random numbers -> ...`

Torch.rand - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [45]:
# create a random tensor of size [3, 4]

random_tensor = torch.rand(3, 4)

In [46]:
random_tensor

tensor([[0.8381, 0.1269, 0.2956, 0.6111],
        [0.9133, 0.3861, 0.3615, 0.4154],
        [0.2373, 0.4520, 0.8188, 0.4292]])

In [47]:
random_tensor.ndim

2

In [48]:
random_tensor_2 = torch.rand(10, 10, 10)
random_tensor_2

tensor([[[5.5810e-01, 8.1153e-01, 2.2166e-01, 7.3159e-01, 9.2164e-01,
          1.3807e-01, 9.5321e-01, 6.8722e-01, 5.0328e-01, 1.9188e-01],
         [9.8170e-01, 6.3510e-01, 1.1387e-01, 6.1483e-01, 7.1949e-02,
          7.1159e-02, 1.3223e-01, 6.3685e-01, 8.8020e-01, 1.7159e-01],
         [4.2251e-01, 4.4717e-01, 9.0490e-01, 6.2512e-01, 9.6489e-01,
          7.1204e-01, 8.1187e-01, 1.6285e-01, 8.0806e-01, 5.8229e-01],
         [2.3469e-01, 2.8426e-01, 6.4894e-01, 3.6709e-02, 2.7236e-01,
          3.8071e-01, 3.5528e-01, 7.4395e-01, 1.9360e-01, 7.9133e-01],
         [2.9642e-01, 4.4150e-01, 7.2554e-01, 1.9960e-02, 8.0021e-01,
          3.1619e-01, 3.9187e-01, 1.2786e-01, 8.6315e-01, 3.5888e-02],
         [5.1303e-01, 8.5028e-01, 2.6829e-01, 2.3470e-01, 6.5624e-01,
          1.0638e-01, 6.7576e-01, 1.0237e-01, 2.4302e-01, 7.6693e-01],
         [2.7844e-01, 5.2663e-01, 7.8059e-01, 7.0728e-01, 9.7746e-01,
          6.8681e-01, 3.0640e-01, 4.7335e-01, 2.2949e-02, 2.9137e-01],
         [8.3

In [49]:
random_tensor_2.ndim

3

In [54]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
# height, width, color channels(rgb)
random_image_size_tensor.shape, random_image_size_tensor.size(), random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

### zeros and ones tensor


In [61]:
# creating a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [62]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [59]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [63]:
ones * random_tensor

tensor([[0.8381, 0.1269, 0.2956, 0.6111],
        [0.9133, 0.3861, 0.3615, 0.4154],
        [0.2373, 0.4520, 0.8188, 0.4292]])

In [69]:
random_tensor.sum(axis = 0)

tensor([1.9888, 0.9649, 1.4760, 1.4557])

In [70]:
ones.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [72]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
zero_to_thousand_step_77 = torch.arange(start=0,
                                        end =  1000,
                                        step= 77                      
                                        )
zero_to_thousand_step_77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [78]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

- **Note:** Tensor datatypes is one of the 3 big erros you'll run into PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device
   1. 如果两个TensorFlow不在一个设备上，一个在CPU上，一个在GPU上

In [85]:
float_32_tensor = torch.tensor([1, 2, 3],
                               device="cuda", # What device is your tensor on
                               dtype=float, # What datatype is the tensor
                               requires_grad=True) # Whether or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float64