## What is a Tensor?

### 创建一个tensor

- 常量和向量通常用小写字母来表示
- 矩阵和张量通常用大写字母来表示

In [2]:
import torch

In [3]:
print(torch.__version__)

2.4.1


In [4]:
# 创建一个常量，值为7，0维张量
scalar = torch.tensor(7)

In [5]:
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
TENSOR = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]]])

In [8]:
TENSOR

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [9]:
TENSOR.ndim

4

In [10]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [11]:
TENSOR[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR[0][0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [13]:
TENSOR[0][0][0]

tensor([1, 2, 3])

In [14]:
TENSOR[0][0][0][0]

tensor(1)

### 创建一个random tensor

- 为什么要使用random tensor呢？
- 因为许多神经网络的训练都是从random tensor开始的，随机的数能更好的表示数据

`start with random numbers -> look at data -> update random numebrs -> look at data -> update random numbers -> ...`

Torch.rand - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [15]:
# create a random tensor of size [3, 4]

random_tensor = torch.rand(3, 4)

In [16]:
random_tensor

tensor([[0.3632, 0.0415, 0.1076, 0.9639],
        [0.2570, 0.4270, 0.7744, 0.1142],
        [0.4779, 0.1927, 0.1899, 0.0685]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor_2 = torch.rand(10, 10, 10)
random_tensor_2

tensor([[[0.3308, 0.1415, 0.5030, 0.3613, 0.6540, 0.8336, 0.5508, 0.8638,
          0.4653, 0.1254],
         [0.4926, 0.4523, 0.4167, 0.2569, 0.4846, 0.8637, 0.4237, 0.8850,
          0.3151, 0.0142],
         [0.2854, 0.7155, 0.9417, 0.8119, 0.1542, 0.1588, 0.9664, 0.4667,
          0.6105, 0.5095],
         [0.4363, 0.5503, 0.2518, 0.7999, 0.7144, 0.5724, 0.3987, 0.1883,
          0.5680, 0.8450],
         [0.3953, 0.1621, 0.1947, 0.5358, 0.2095, 0.0667, 0.1309, 0.6713,
          0.4320, 0.6596],
         [0.1304, 0.4189, 0.0031, 0.3603, 0.3798, 0.2859, 0.8934, 0.7223,
          0.5009, 0.4970],
         [0.6854, 0.1719, 0.1607, 0.1517, 0.0559, 0.4965, 0.0301, 0.8852,
          0.5914, 0.1151],
         [0.5693, 0.7134, 0.5214, 0.2961, 0.5516, 0.6435, 0.3989, 0.7839,
          0.4686, 0.3171],
         [0.2603, 0.9124, 0.4190, 0.5710, 0.5978, 0.7419, 0.9724, 0.2257,
          0.2878, 0.3130],
         [0.5200, 0.8792, 0.6587, 0.2655, 0.6310, 0.9515, 0.9581, 0.6098,
          0.0817,

In [19]:
random_tensor_2.ndim

3

In [20]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
# height, width, color channels(rgb)
random_image_size_tensor.shape, random_image_size_tensor.size(), random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

### zeros and ones tensor


In [21]:
# creating a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones * random_tensor

tensor([[0.3632, 0.0415, 0.1076, 0.9639],
        [0.2570, 0.4270, 0.7744, 0.1142],
        [0.4779, 0.1927, 0.1899, 0.0685]])

In [25]:
random_tensor.sum(axis = 0)

tensor([1.0981, 0.6613, 1.0719, 1.1466])

In [26]:
ones.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [27]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
zero_to_thousand_step_77 = torch.arange(start=0,
                                        end =  1000,
                                        step= 77                      
                                        )
zero_to_thousand_step_77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [29]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

- **Note:** Tensor datatypes is one of the 3 big erros you'll run into PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device
   1. 如果两个TensorFlow不在一个设备上，一个在CPU上，一个在GPU上

### Getting information from tensors(tensor attributes)

1. to get datatype from a tensor —— use `tensor.dtype`
2. to get shape from a tensor —— use `tensor.shape`
3. to get device from a tensor —— use `tensor.device`

In [30]:
float_32_tensor = torch.tensor([1, 2, 3],
                               device="cuda", # What device is your tensor on
                               dtype=torch.float32, # What datatype is the tensor
                               requires_grad=True) # Whether or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float32

In [31]:
float_32_tensor.device

device(type='cuda', index=0)

In [32]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor.dtype

torch.float16

In [33]:
tensor_mul = float_16_tensor * float_32_tensor

In [34]:
tensor_mul.dtype

torch.float32

In [35]:
# Creating a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2707, 0.4844, 0.4808, 0.7118],
        [0.8277, 0.5665, 0.9264, 0.9869],
        [0.6406, 0.3052, 0.2674, 0.8334]])

In [36]:
# Find out details about some tensor

print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2707, 0.4844, 0.4808, 0.7118],
        [0.8277, 0.5665, 0.9264, 0.9869],
        [0.6406, 0.3052, 0.2674, 0.8334]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operation include:
- 加法
- 减法
- 乘法
- 除法
- 矩阵相乘 


In [37]:
# create a tensor

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [38]:
tensor - 100

tensor([-99, -98, -97])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
# multiplication

tensor * 10
tensor

tensor([1, 2, 3])

In [41]:
tensor - 10

tensor([-9, -8, -7])

In [42]:
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


#### Matrix multiplication

two main ways of performing multiplication:
1. element-wise multiplication
2. matrix multiplication

There are two main rules that preforming matrix multiplicatoin needs to satisfy:
1. The **inner dimensions** must match
   1. `(3, 2) @ (3, 2)`报错
   2. `(3, 2) @ (2, 3)` 和 `(2, 3) @ (3, 2)`都不会报错
2. The resulting matrix has the shape of the **outer dimensions**
   1. `(3, 2) @ (2, 3) -> (3, 3)`
   2. `(2, 3) @ (3, 2) -> (2, 2)`  

In [43]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equels: {(tensor * tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equels: tensor([1, 4, 9])


In [44]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 2 ms


tensor(14)

In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 2 ms


tensor(14)

In [46]:
tensor_1 = torch.rand(3, 2)
tensor_2 = torch.rand(2, 3)

In [47]:
%%time
torch.matmul(tensor_1, tensor_2)

CPU times: total: 0 ns
Wall time: 6 ms


tensor([[0.5662, 0.8412, 0.1562],
        [0.1310, 0.1965, 0.0387],
        [0.3997, 0.5935, 0.1097]])

### One of the most common errors in dl: shape errors

In [48]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# torch.mm()
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [49]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### 使用transpose

- 转置

In [201]:
# .T表示transpose

tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [202]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [52]:
# 当B转置之后， 两个矩阵就可以实现矩阵乘法

print(f"tensor_A的形状是{tensor_A.shape}, tensor_B的形状是{tensor_B.shape}")
print(f"B矩阵转置之后，tensor_A的形状是{tensor_A.shape}， tensor_B的形状是{tensor_B.T.shape}")
print(f"Multiplying {tensor_A.shape} @ {tensor_B.T.shape}")
print(f"Output: {torch.mm(tensor_A, tensor_B.T)}")
print(f"Output's Shape: {torch.mm(tensor_A, tensor_B.T).shape}")

tensor_A的形状是torch.Size([3, 2]), tensor_B的形状是torch.Size([3, 2])
B矩阵转置之后，tensor_A的形状是torch.Size([3, 2])， tensor_B的形状是torch.Size([2, 3])
Multiplying torch.Size([3, 2]) @ torch.Size([2, 3])
Output: tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output's Shape: torch.Size([3, 3])


### Finding the max, min, mean, sum, etc(tensor aggregation)

In [56]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [54]:
# Find the min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [55]:
# Find the max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [57]:
# Find the mean
# 输入的张量元素必须是float32

x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
x.type(torch.float32).mean()

tensor(45.)

In [59]:
# Find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [60]:
!pip show torch

Name: torch
Version: 2.4.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: f:\.conda\d2l-zh\lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: torchaudio, torchvision


In [61]:
!pip show d2l

Name: d2l
Version: 1.0.3
Summary: Dive into Deep Learning
Home-page: https://d2l.ai
Author: D2L Developers
Author-email: d2l.devs@gmail.com
License: MIT-0
Location: f:\.conda\d2l-zh\lib\site-packages
Requires: jupyter, matplotlib, matplotlib-inline, numpy, pandas, requests, scipy
Required-by: 


In [62]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

发现了一个区别函数和属性的方法：
- 在提示中
- 属性前面是一个黑板擦
- 方法前面是一个立方体

In [63]:
x.argmin()

tensor(0)

In [65]:
tensor_X = torch.rand(size=(10,2))
tensor_X

tensor([[0.3234, 0.5551],
        [0.4348, 0.6957],
        [0.9572, 0.0127],
        [0.9403, 0.0761],
        [0.1717, 0.8251],
        [0.2687, 0.9575],
        [0.6368, 0.8102],
        [0.6707, 0.2779],
        [0.4250, 0.5594],
        [0.2983, 0.9217]])

In [69]:
# dim=0 表示沿着第0维（行）方向找最小值的索引
# 返回每列的最小值所在的行索引
# 结果是一个形状为[2]的张量，对应tensor_X的两列
tensor_X.argmin(dim=0)

tensor([4, 2])

### Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping: 将输入的tensor改变为指定的形状
- View: 功能与reshape类似，但是返回的是原张量的视图
- Stacking: 将多个张量沿着新的维度堆叠起来
- Squeeze: 移出所有大小为1的维度
- Unsqueeze: 在指定位置添加一个大小为1的维度
- Permute: 改变张量的维度顺序

In [70]:
x = torch.arange(1, 10, dtype=torch.float32)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
x.reshape(3, 3), x.size()

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([9]))

In [74]:
# Change the view
z = x.view(1, 9)
z, z.shape()

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
# changing z changes x (because a viwe of z shares the same memory as the original input)
z[0][0] = 5
z

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [76]:
x

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [79]:
x_stacked_1 = torch.stack([x, x, x, x], dim=1)
x_stacked_1

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [82]:
x_reshaped = torch.arange(1., 10.)
x_reshaped, x_reshaped.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [85]:
x_reshaped = x_reshaped.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [88]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape
x_squeezed = x_reshaped.squeeze()

In [90]:
# torch.unsqueezed() -- adda a single dimension to a target tensor at a specific dim

print(f"Previous squeezed target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")


# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


x_unsqueezed_1 = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed_1}")
print(f"New shape: {x_unsqueezed_1.shape}")

Previous squeezed target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])

New tensor: tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [93]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original =  torch.rand(size=(3, 4, 5))
x_original.shape

torch.Size([3, 4, 5])

In [94]:
# 使用permute操作
# 将原来第2维度的放在新的第0维度
# 原来第0维度放在新的第1维度
# 原来第1维度放在新的第2维度
x_permuted = x_original.permute(2, 0, 1)
x_permuted.shape

torch.Size([5, 3, 4])

### Indexing(selecting data from tensors)


In [97]:
x = torch.arange(1, 10).reshape(shape=(1, 3, 3))
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [99]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [102]:
x[0][0][0]

tensor(1)

In [103]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [104]:
x[:, 1]

tensor([[4, 5, 6]])

In [105]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [106]:
x[:, 1, 1]

tensor([5])

In [107]:
x[0, 0, :]

tensor([1, 2, 3])