## What is a Tensor?

### 创建一个tensor

- 常量和向量通常用小写字母来表示
- 矩阵和张量通常用大写字母来表示

In [151]:
import torch

In [152]:
print(torch.__version__)

2.4.1


In [153]:
# 创建一个常量，值为7，0维张量
scalar = torch.tensor(7)

In [154]:
scalar

tensor(7)

In [155]:
scalar.ndim

0

In [156]:
TENSOR = torch.tensor([[[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]]])

In [157]:
TENSOR

tensor([[[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [158]:
TENSOR.ndim

4

In [159]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [160]:
TENSOR[0]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [161]:
TENSOR[0][0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [162]:
TENSOR[0][0][0]

tensor([1, 2, 3])

In [163]:
TENSOR[0][0][0][0]

tensor(1)

### 创建一个random tensor

- 为什么要使用random tensor呢？
- 因为许多神经网络的训练都是从random tensor开始的，随机的数能更好的表示数据

`start with random numbers -> look at data -> update random numebrs -> look at data -> update random numbers -> ...`

Torch.rand - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [164]:
# create a random tensor of size [3, 4]

random_tensor = torch.rand(3, 4)

In [165]:
random_tensor

tensor([[0.0581, 0.0493, 0.3359, 0.9141],
        [0.7459, 0.0298, 0.9468, 0.6498],
        [0.8517, 0.0823, 0.8929, 0.5253]])

In [166]:
random_tensor.ndim

2

In [167]:
random_tensor_2 = torch.rand(10, 10, 10)
random_tensor_2

tensor([[[1.3761e-01, 7.4813e-01, 3.3788e-02, 9.6627e-01, 9.7242e-01,
          6.8463e-01, 4.4086e-01, 9.2388e-01, 4.7733e-01, 5.4618e-01],
         [3.7378e-02, 4.2903e-01, 1.2524e-01, 2.2315e-01, 5.4925e-01,
          7.2545e-01, 1.9072e-01, 1.1322e-02, 6.6007e-01, 8.5753e-01],
         [1.5000e-01, 2.2707e-01, 9.0371e-01, 7.2611e-02, 6.6361e-01,
          7.5018e-01, 3.3396e-02, 5.2012e-01, 6.4296e-01, 9.1645e-01],
         [6.4057e-01, 2.2057e-02, 3.8725e-01, 3.2638e-01, 5.8521e-01,
          6.8924e-01, 4.8513e-01, 9.9436e-01, 8.2619e-01, 7.9822e-01],
         [3.8078e-02, 9.6516e-01, 9.2962e-01, 2.2861e-01, 6.1710e-01,
          7.0955e-01, 8.0507e-01, 3.4282e-01, 4.9378e-01, 4.4742e-01],
         [3.5184e-01, 4.6387e-01, 6.1127e-01, 4.7312e-01, 6.4511e-01,
          4.5175e-02, 7.0935e-01, 3.6769e-01, 1.3374e-02, 5.8210e-01],
         [4.8741e-01, 3.6129e-02, 8.0604e-01, 3.7783e-01, 4.8415e-02,
          5.8411e-01, 4.2908e-01, 8.5638e-01, 6.8156e-01, 7.5466e-01],
         [4.8

In [168]:
random_tensor_2.ndim

3

In [169]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
# height, width, color channels(rgb)
random_image_size_tensor.shape, random_image_size_tensor.size(), random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), torch.Size([224, 224, 3]), 3)

### zeros and ones tensor


In [170]:
# creating a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [171]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [172]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [173]:
ones * random_tensor

tensor([[0.0581, 0.0493, 0.3359, 0.9141],
        [0.7459, 0.0298, 0.9468, 0.6498],
        [0.8517, 0.0823, 0.8929, 0.5253]])

In [174]:
random_tensor.sum(axis = 0)

tensor([1.6558, 0.1614, 2.1755, 2.0892])

In [175]:
ones.dtype

torch.float32

### Creating a range of tensor and tensors-like

In [176]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [177]:
zero_to_thousand_step_77 = torch.arange(start=0,
                                        end =  1000,
                                        step= 77                      
                                        )
zero_to_thousand_step_77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [178]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

- **Note:** Tensor datatypes is one of the 3 big erros you'll run into PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device
   1. 如果两个TensorFlow不在一个设备上，一个在CPU上，一个在GPU上

### Getting information from tensors(tensor attributes)

1. to get datatype from a tensor —— use `tensor.dtype`
2. to get shape from a tensor —— use `tensor.shape`
3. to get device from a tensor —— use `tensor.device`

In [179]:
float_32_tensor = torch.tensor([1, 2, 3],
                               device="cuda", # What device is your tensor on
                               dtype=torch.float32, # What datatype is the tensor
                               requires_grad=True) # Whether or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float32

In [180]:
float_32_tensor.device

device(type='cuda', index=0)

In [181]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor.dtype

torch.float16

In [182]:
tensor_mul = float_16_tensor * float_32_tensor

In [183]:
tensor_mul.dtype

torch.float32

In [184]:
# Creating a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1993, 0.8973, 0.0529, 0.6850],
        [0.1446, 0.1627, 0.0240, 0.5047],
        [0.8065, 0.6677, 0.3098, 0.3790]])

In [185]:
# Find out details about some tensor

print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1993, 0.8973, 0.0529, 0.6850],
        [0.1446, 0.1627, 0.0240, 0.5047],
        [0.8065, 0.6677, 0.3098, 0.3790]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operation)

Tensor operation include:
- 加法
- 减法
- 乘法
- 除法
- 矩阵相乘 


In [186]:
# create a tensor

tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [187]:
tensor - 100

tensor([-99, -98, -97])

In [188]:
tensor

tensor([1, 2, 3])

In [189]:
# multiplication

tensor * 10
tensor

tensor([1, 2, 3])

In [190]:
tensor - 10

tensor([-9, -8, -7])

In [191]:
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])


#### Matrix multiplication

two main ways of performing multiplication:
1. element-wise multiplication
2. matrix multiplication

There are two main rules that preforming matrix multiplicatoin needs to satisfy:
1. The **inner dimensions** must match
   1. `(3, 2) @ (3, 2)`报错
   2. `(3, 2) @ (2, 3)` 和 `(2, 3) @ (3, 2)`都不会报错
2. The resulting matrix has the shape of the **outer dimensions**
   1. `(3, 2) @ (2, 3) -> (3, 3)`
   2. `(2, 3) @ (3, 2) -> (2, 2)`  

In [192]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equels: {(tensor * tensor)}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equels: tensor([1, 4, 9])


In [193]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [194]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 965 µs


tensor(14)

In [196]:
tensor_1 = torch.rand(3, 2)
tensor_2 = torch.rand(2, 3)

In [197]:
%%time
torch.matmul(tensor_1, tensor_2)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[1.0615, 0.3679, 1.0310],
        [0.6788, 0.3905, 0.8700],
        [0.4919, 0.2136, 0.5362]])

### One of the most common errors in dl: shape errors

In [199]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

# torch.mm()
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [200]:
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### 使用transpose

- 转置

In [201]:
# .T表示transpose

tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [202]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])